### PR TITLE
Store devise secret_key in an environment variable

### PR DESCRIPTION
**Pull request by bishboria**
Part of upgrading devise.

Previous `secret_key` was auto-generated. Load the key from an environment variable instead.

### CODE REVIEW

**Comment by bradleywright** [comment]
This will need a PR in Puppet to add the environment variable. Let's do that first before we merge this.

**Comment by bishboria** [comment]
We're working on that right now

**Comment by boffbowsh** [comment]
:+1:. I thought about suggesting a default for if that env var isn't set, but I guess it's better for it to fail loudly.

**Comment by bradleywright** [comment]
I think we can merge this now?

**Pull request merged**
