### PR TITLE
Replacement department name with locale lookup.

### PR DESCRIPTION
**Pull request by dwhenry**
This is the last piece of work to allow pension wise to merge our branch back in.

We still have some differences, which I will leave within our branch :

- Using Postgres instead of MySQL - existing branch attempting to solve this issue.
- Using Puma instead of Unicorn.
- Using Bugsnag instead of Airbrake.
- Adding Newrelic logging
- Using Rails12Factor instead of LogStasher
- Upgrade of SideKiq to v 4.0

Let me know if you think any should be merged in (or written to allow either to be used).

David

### CODE REVIEW

**Comment by benlovell** [comment]
Can you reword b5a4ccd to include _why_ you're making this change?

**Comment by benlovell** [comment]
Of those other differences you're maintaining:

* #467 is pending and will make us database-agnostic. 
* We'll eventually upgrade sidekiq

But the rest are not likely to be pulled upstream anytime soon.

**Comment by dwhenry** [comment]
@benlovell updated commit message. 

Your comments on difference is inline with expectations.

**Comment by benlovell** [comment]
Thanks :+1:

**Pull request merged**
