### PR TITLE
Add 2SV status filtering to User list.

### PR DESCRIPTION
**Pull request by gpeng**
https://trello.com/c/JpTKA5M5

This PR may be better reviewed commit by commit.

Before changes showing original UI
===========================

before_changes

After changes showing filter and new 2SV Status column
===========================================

after_changes

### CODE REVIEW

**Comment by fofr** [comment]
I'm not keen on the use of "2SV" in the UI, though I can't think of an alternative. Where it's used can there be an `<abbr>` tag which explains the abbreviation?

**Comment by benlovell** [comment]
@boffbowsh Addressed in f213840

**Comment by benlovell** [comment]
@fofr Addressed in 764c49d

screen shot 2016-01-06 at 16 22 21

**Comment by boffbowsh** [comment]
:+1: from me, will let @fofr merge if he's happy

**Comment by fofr** [comment]
:+1:

**Comment by jamiecobbett** [comment]
:fireworks:

**Pull request merged**
