### PR TITLE
YAML secrets for Devise

### PR DESCRIPTION
**Pull request by alexmuller**
Depends on https://github.com/alphagov/govuk-puppet/pull/4877 and https://github.gds/gds/deployment/pull/1083 being in production.

I think this approach is safer than what we have at the moment.

### CODE REVIEW

**Comment by boffbowsh** [comment]
This will want a rebase against master

**Comment by alexmuller** [comment]
Rebased, and this is ready to be reviewed now:

```
fab staging class:backend do:'cat /etc/govuk/signon/env.d/DEVISE_PEPPER'
fab staging class:backend do:'cat /etc/govuk/signon/env.d/DEVISE_SECRET_KEY'
fab production class:backend do:'cat /etc/govuk/signon/env.d/DEVISE_PEPPER'
fab production class:backend do:'cat /etc/govuk/signon/env.d/DEVISE_SECRET_KEY'
```

**Comment by boffbowsh** [comment]
Looks like we're waiting on the new pepper being deployed.

**Comment by alexmuller** [comment]
Interesting, that's working for me. Is it not for you?

**Comment by boffbowsh** [comment]
The pepper is the same in staging and production, is that correct? But I have now just realised the point of the other PRs is to introduce the env var in the first place, not to change them. So, if they're expected to be the same, 👍

**Comment by alexmuller** [comment]
Yep, that's right. It has to be the same because it's used to encrypt passwords which are synced with the database overnight.

**Comment by alexmuller** [comment]
Tests aren't running here for some reason, will see what's going on.

**Comment by alexmuller** [comment]
https://ci.dev.publishing.service.gov.uk/job/govuk_gds_sso_signon_branches/544/console is still failing for some reason.

**Comment by alexmuller** [comment]
In order to get the gds-sso tests to pass here I had to temporarily change the gds-sso branch name on CI to use alphagov/gds-sso@d2885dfc9cff1c923c0c4e4acb936e031df41d73.

**Pull request merged**
