### PR TITLE
Remove Share Sale Publisher

### PR DESCRIPTION
**Pull request by steventux**
This application doesn't exist any more so remove it from Signon

### CODE REVIEW

**Comment by alexmuller** [comment]
How much data will this get rid of? I'm thinking mostly of audit logs.

**Comment by steventux** [comment]
ok I will have a look into this, might be better to do a soft delete.

**Comment by steventux** [comment]
@alexmuller this should soft-delete now because https://github.com/alphagov/signonotron2/pull/527

**Comment by alexmuller** [comment]
Looks like magic to me! Will let somebody else who knows more Rails than me have a read too.

**Pull request merged**
