### PR TITLE
Allow adding a note to a user when editing.

### PR DESCRIPTION
**Pull request by elliotcm**
DO NOT MERGE BEFORE https://github.com/alphagov/signonotron2/pull/298

Allows tracking of training, reasons for granting
or revoking specific permissions etc.

Requested by GOV.UK content team.

- [x] Data input
- [ ] Data output

screenshot 2015-01-21 13 05 55

### CODE REVIEW

**Comment by rboulton** [comment]
Seems good, but tests failed.

**Comment by alext** [comment]
Also, can we hold off merging while #298 is being tested on preview.

**Comment by fofr** [comment]
I'd love to see some screenshots too.

**Comment by vinayvinay** [comment]
0. worth considering whether this information should be an entry in the user's event log, instead of storing it as a `note`.
0. how are we thinking of sharing these notes with the GOV.UK content team when they want it? i'm guessing it wouldn't be very costly to surface this on a page that's linked from the user's edit page.

**Comment by elliotcm** [comment]
@rboulton Thanks, I'll sort them out.

@alext No problem.  Added a warning.

@fofr I've added a screenshot of the entry form, I'll add another of the display once it's done.

@vinayvinay 
1. Worth investigating.  I'll take a look now.
2. I was planning on doing that as another PR but it makes as much sense as part of this one.  I'll set it up.

**Comment by elliotcm** [comment]
The scope of this has been changed last minute.  I'll do a new PR once it's all changed.

**Pull request closed without merging**
